config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: redirect("/dashboard"), as: :authenticated_root
  end
  root to: redirect("/users/sign_in")

  devise_for :users

  resource :dashboard, only: :show, controller: "dashboard"
  resource :privacy_policy, only: :show, controller: "privacy_policy"
  resource :profile, only: :show, controller: "users"
  resource :leaderboard, only: :show, controller: "leaderboard"

  resources :locations, param: :slug
  resources :killers, param: :slug
  resources :series, only: %i[index new create edit update]
  resources :plays
  resources :users, only: %i[show update]
  resources :user_final_girls
end

app/models/user_final_girl.rb
class UserFinalGirl < ApplicationRecord
  belongs_to :user
  belongs_to :final_girl
end

app/controllers/user_final_girls_controller.rb
class UserFinalGirlsController < AuthController
  def index
    @facade = UserFinalGirl::IndexFacade.new current_user
  end

  def new
    @facade = UserFinalGirl::NewFacade.new current_user
  end

  def create
    @facade = UserFinalGirl::NewFacade.new current_user, params, strong_params: strong_params
    if @facade.model.save
      redirect_to user_final_girls_url, notice: "Final Girl was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @facade = UserFinalGirl::EditFacade.new current_user, params
  end

  def update
    @facade = UserFinalGirl::EditFacade.new current_user, params, strong_params: strong_params
    if @facade.model.save
      redirect_to user_final_girls_url, notice: "Final Girl was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    final_girl.destroy
    redirect_to user_final_girls_url, notice: "Final Girl was successfully destroyed.", status: :see_other
  end

  private

  def final_girl
    @final_girl = current_user.final_girls.find_by(id: params[:id])
  end

  def final_girl_params
    params.require(:final_girl).permit(:name)
  end

  def strong_params
    {
      name: final_girl_params[:name],
      slug: final_girl_params[:name].parameterize
    }
  end
end

app/helpers/user_final_girls_helper.rb
module UserFinalGirlsHelper
end

app/views/user_final_girls/_form.html.erb
<%= form_with model: [:user, model], class: "contents" do |form| %>
  <%= form.errors model %>
  <div class="flex flex-col">
    <div class="mb-4">
      <%= form.label :name %>
      <%= form.text_field :name, autofocus: true %>
    </div>
  </div>
  <div class="mt-12 flex flex-row justify-end">
    <%= link_to "Back", user_final_girls_path, class: "button bg-transparent hover:bg-zinc-800 mr-2" %>
    <%= form.submit "Save" %>
  </div>
<% end %>

app/views/user_final_girls/_user_final_girl.html.erb
<tr id="<%= dom_id user_final_girl %>" class="odd:bg-zinc-600 even:bg-zinc-700 text-zinc-50 flex flex-col relative sm:table-row first:rounded-t-lg last:rounded-b-lg">
  <td class="text-left md:py-3 px-4">
    <div class="flex flex-row items-center">
      <span class="font-bold"><%= user_final_girl.name %></span>
    </div>
  </td>
  <td class="py-3 px-4 absolute top-0 right-0 sm:relative">
    <div class="flex justify-end items-center">
      <%= link_to edit_user_final_girl_path(user_final_girl), class: "button h-7 w-7 bg-transparent hover:bg-zinc-800 mr-2" do %>
        <i class="fa-solid fa-pen-to-square"></i>
      <% end %>
      <%= button_to user_final_girl_path(user_final_girl), method: :delete, class: "button h-7 w-7 bg-transparent hover:bg-primary", form: { data: { turbo_confirm: "Are you sure you want to delete this final girl?" } } do %>
        <i class="fa-solid fa-trash-can"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/user_final_girls/edit.html.erb
<div class="container mx-auto lg:w-1/3">
  <div class="text-zinc-50 relative flex flex-col mt-4">
    <h1 class="font-display text-3xl mb-4">Edit Final Girl</h1>
    <%= render "form", model: @facade.model %>
  </div>
</div>

app/views/user_final_girls/index.html.erb
<div class="text-zinc-50 flex flex-row justify-between items-center mb-4 w-full">
  <h1 class="font-display text-primary text-4xl">My Final Girls</h1>
  <%= link_to "Add Final Girl", new_user_final_girl_path, class: "button" %>
</div>
<table class="table-auto border-collapse min-w-full text-white">
  <thead class="hidden sm:table-header-group">
    <tr>
      <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Final Girl</th>
      <th class="text-center py-3 px-4 uppercase font-semibold text-sm"></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "user_final_girl", collection: @facade.collection %>
  </tbody>
</table>

app/views/user_final_girls/new.html.erb
<div class="container mx-auto lg:w-1/3">
  <div class="text-zinc-50 relative flex flex-col mt-4">
    <h1 class="font-display text-3xl mb-4">Create Final Girl</h1>
    <%= render "form", model: @facade.model %>
  </div>
</div>