config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: redirect("/dashboard"), as: :authenticated_root
  end
  root to: redirect("/users/sign_in")

  devise_for :users

  resource :dashboard, only: :show, controller: "dashboard"
  resource :privacy_policy, only: :show, controller: "privacy_policy"
  resource :profile, only: :show, controller: "users"
  resource :leaderboard, only: :show, controller: "leaderboard"

  resources :locations, param: :slug
  resources :killers, param: :slug
  resources :series, only: %i[index new create edit update]
  resources :plays
  resources :users, only: %i[show update]
  resources :user_final_girls
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :user
  belongs_to :final_girl
  belongs_to :killer
  belongs_to :location
end

app/controllers/plays_controller.rb
class PlaysController < AuthController
  def index
    @facade = Play::IndexFacade.new current_user
  end

  def new
    @facade = Play::NewFacade.new current_user
  end

  def create
    @facade = Play::NewFacade.new current_user, play_params

    if @facade.model.save
      redirect_to plays_url, notice: "Play was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @facade = Play::EditFacade.new current_user, params
  end

  def update
    @facade = Play::EditFacade.new current_user, params, strong_params: play_params

    if @facade.model.save
      redirect_to plays_url, notice: "Play was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    play.destroy

    redirect_to plays_url, notice: "Play was successfully destroyed.", status: :see_other
  end

  private

  def play
    @play ||= Play.find(params[:id])
  end

  def play_params
    params.require(:play).permit(
      :final_girl_id,
      :killer_id,
      :location_id,
      :created_at,
      :is_win,
      :extreme_horror_mode
    )
  end
end

app/views/plays/_form.html.erb
<%= form_with model: facade.model, class: "contents" do |form| %>
  <%= form.errors facade.model %>
  <div class="flex flex-col">
    <div class="mb-4">
      <%= form.label :final_girl_id, "Final Girl" %>
      <%= form.grouped_collection_select :final_girl_id, facade.grouped_final_girl_options, :last, :first, :last, :first, { prompt: "Select a Final Girl" }, class: "w-full mt-1", required: true %>
    </div>
    <div class="mb-4">
      <%= form.label :killer_id, class: "mb-2" %>
      <%= form.grouped_collection_select :killer_id, facade.series, :ordered_killers, :name, :id, :name, { prompt: "Select a Killer"}, include_blank: true, class: "w-full mt-1" %>
    </div>
    <div class="mb-4">
      <%= form.label :location_id, class: "mb-2" %>
      <%= form.grouped_collection_select :location_id, facade.series, :ordered_locations, :name, :id, :name, { prompt: "Select a Location"}, include_blank: true, class: "w-full mt-1" %>
    </div>
    <div class="mb-4">
      <%= form.label :created_at, "Play Date", class: "mb-2" %>
      <div class="w-full">
        <%= form.datetime_local_field :created_at, class: "bg-zinc-900 text-white rounded-md border-zinc-800 focus:ring-primary focus:border-transparent py-1 w-full mt-1", required: true, step: "1"  %>
      </div>
    </div>
    <div class="mb-4">
      <%= form.label :is_win, "Won?", class: "flex items-center" do %>
        <%= form.check_box :is_win, class: "mr-2 rounded" %>
        Won?
      <% end %>
    </div>
    <div class="mb-4">
      <%= form.label :extreme_horror_mode, "Extreme Horror Mode?", class: "flex items-center" do %>
        <%= form.check_box :extreme_horror_mode, class: "mr-2 rounded" %>
        Extreme Horror Mode?
      <% end %>
    </div>
  </div>
  <div class="mt-12 flex flex-row justify-end">
    <%= link_to "Back", plays_path, class: "button bg-transparent hover:bg-zinc-800 mr-2" %>
    <%= form.submit "Save" %>
  </div>
<% end %>

app/views/plays/_play.html.erb
<tr id="<%= dom_id play %>" class="odd:bg-zinc-600 even:bg-zinc-700 text-zinc-50 flex flex-col relative sm:table-row first:rounded-t-lg last:rounded-b-lg">
  <td class="text-left py-3 px-4">
    <div class="flex flex-col">
      <span><%= play.created_at.to_fs(:long) %></span>
      <span class="text-sm text-zinc-400"><%= time_ago_in_words play.created_at %> ago</span>
    </div>
  </td>
  <td class="text-left md:py-3 px-4">
    <div class="flex flex-row items-center">
      <span class="font-bold"><%= play.final_girl.name %></span>
    </div>
  </td>
  <td class="text-left md:py-3 px-4">
    <div class="flex flex-row items-center">
      <% if play.killer.icon.attached? %>
        <div class="mr-2 h-5 w-5 sm:w-7 sm:h-7">
          <%= image_tag rails_blob_path(play.killer.icon), class: "aspect-square w-5 sm:w-7" %>
        </div>
      <% end %>
      <span class="font-bold"><%= play.killer.name %></span>
    </div>
  </td>
  <td class="text-left pb-3 md:py-3 px-4">
    <div class="flex flex-row items-center">
      <% if play.location.icon.attached? %>
        <div class="mr-2 h-5 w-5 sm:w-7 sm:h-7">
          <%= image_tag rails_blob_path(play.location.icon), class: "aspect-square w-5 sm:w-7" %>
        </div>
      <% end %>
      <span class="font-bold"><%= play.location.name %></span>
    </div>
  </td>
  <td class="py-3 px-4 pb-3 absolute bottom-8 right-1 sm:bottom-0 sm:relative">
    <div class="flex md:justify-center items-center">
      <% if play.is_win %>
        <%= image_tag asset_path('recover-health.png'), class: "aspect-square h-7" %>
      <% else %>
        <%= image_tag asset_path('lose-health.png'), class: "aspect-square h-7" %>
      <% end %>
    </div>
  </td>
  <td class="py-3 px-4 pb-3 absolute bottom-0 right-1 sm:relative">
    <div class="flex md:justify-center items-center">
      <% if play.extreme_horror_mode %>
        <%= image_tag asset_path('horror.png'), class: "aspect-square h-7" %>
      <% else %>
        <%= image_tag asset_path('lose_horror.png'), class: "aspect-square h-7" %>
      <% end %>
    </div>
  </td>
  <td class="py-3 px-4 absolute top-0 right-0 sm:relative">
    <div class="flex justify-center items-center">
      <%= link_to edit_play_path(play), class: "button h-7 w-7 bg-transparent hover:bg-zinc-800 mr-2" do %>
        <i class="fa-solid fa-pen-to-square"></i>
      <% end %>
      <%= button_to play_path(play), method: :delete, class: "button h-7 w-7 bg-transparent hover:bg-primary", form: { data: { turbo_confirm: "Are you sure you want to delete this play?" } } do %>
        <i class="fa-solid fa-trash-can"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/plays/edit.html.erb
<div class="container mx-auto lg:w-1/3">
  <div class="text-zinc-50 relative flex flex-col mt-4">
    <h1 class="font-display text-3xl mb-4">Log a Play</h1>
    <%= render "form", facade: @facade %>
  </div>
</div>

app/views/plays/index.html.erb
<div class="text-zinc-50 flex flex-row justify-between items-center mb-4 w-full">
  <%= render PageTitleComponent.new title: "Play Log" %>
  <%= link_to 'Add Play', new_play_path, class: "button" %>
</div>
<table class="table-auto border-collapse min-w-full text-white">
  <thead class="hidden sm:table-header-group">
    <tr>
      <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Date</th>
      <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Final Girl</th>
      <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Killer</th>
      <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Location</th>
      <th class="text-center py-3 px-4 uppercase font-semibold text-sm">Won?</th>
      <th class="text-center py-3 px-4 uppercase font-semibold text-sm">EHM?</th>
      <th class="text-center py-3 px-4 uppercase font-semibold text-sm"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @facade.plays %>
  </tbody>
</table>

app/views/plays/new.html.erb
<div class="container mx-auto lg:w-1/3">
  <div class="text-zinc-50 relative flex flex-col mt-4">
    <h1 class="font-display text-3xl mb-4">Log a Play</h1>
    <%= render "form", facade: @facade %>
  </div>
</div>