config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: redirect("/dashboard"), as: :authenticated_root
  end
  root to: redirect("/users/sign_in")

  devise_for :users

  resource :dashboard, only: :show, controller: "dashboard"
  resource :privacy_policy, only: :show, controller: "privacy_policy"
  resource :profile, only: :show, controller: "users"
  resource :leaderboard, only: :show, controller: "leaderboard"

  resources :locations, param: :slug
  resources :killers, param: :slug
  resources :series, only: %i[index new create edit update]
  resources :plays
  resources :users, only: %i[show update]
  resources :user_final_girls
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
    :validatable

  has_many :plays

  has_many :user_killer_achievements
  has_many :killer_achievements, through: :user_killer_achievements

  has_many :user_location_achievements
  has_many :location_achievements, through: :user_location_achievements

  has_many :user_final_girls, inverse_of: :user, dependent: :destroy
  has_many :final_girls, through: :user_final_girls

  accepts_nested_attributes_for :user_killer_achievements
  accepts_nested_attributes_for :user_location_achievements
end

app/controllers/users_controller.rb
class UsersController < AuthController
  def show
  end

  def update
    current_user.update!(user_params)
    flash.notice = "Your changes have been saved."

    redirect_back(fallback_location: root_path)
  end

  def user_params
    params.require(:user).permit(
      :username,
      {
        user_killer_achievements_attributes: %i[
          id
          killer_achievement_id
          location_id
          completed
        ],
      },
      {
        user_location_achievements_attributes: %i[
          id
          location_achievement_id
          killer_id
          completed
        ],
      },
    )
  end
end

app/views/users/show.html.erb
<%= render PageTitleComponent.new title: "User Profile" %>
<div class="w-full sm:w-96 mt-8 text-zinc-50">
  <%= form_for @user do |f| %>
    <div class="mb-4">
      <%= f.label :email do %>
        Email <span class="text-sm text-primary">cannot be changed</span>
      <% end %>
      <%= f.text_field :email, readonly: true %>
    </div>
    <div class="mb-4">
      <%= f.label :username, "Display Name" %>
      <%= f.text_field :username, autofocus: true %>
    </div>
    <div class="mt-12 flex flex-row justify-end">
      <%= link_to "Back", dashboard_path, class: "button bg-transparent hover:bg-zinc-800 mr-2" %>
      <%= f.submit %>
    </div>
  <% end %>
</div>