config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: redirect("/dashboard"), as: :authenticated_root
  end
  root to: redirect("/users/sign_in")

  devise_for :users

  resource :dashboard, only: :show, controller: "dashboard"
  resource :privacy_policy, only: :show, controller: "privacy_policy"
  resource :profile, only: :show, controller: "users"
  resource :leaderboard, only: :show, controller: "leaderboard"

  resources :locations, param: :slug
  resources :killers, param: :slug
  resources :series, only: %i[index new create edit update]
  resources :plays
  resources :users, only: %i[show update]
  resources :user_final_girls
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/final_girl.rb
class FinalGirl < ApplicationRecord
  has_one :final_girl_series, dependent: :destroy
  has_one :user_final_girl, dependent: :destroy
  has_one :series, through: :final_girl_series
  has_one :user, through: :user_final_girl

  validates :name, presence: true
end

app/models/final_girl_series.rb
class FinalGirlSeries < ApplicationRecord
  belongs_to :final_girl
  belongs_to :series
end

app/models/killer.rb
class Killer < ApplicationRecord
  belongs_to :series
  has_many :achievements, class_name: "KillerAchievement"
  has_one_attached :logo
  has_one_attached :icon

  validates :name, presence: true

  def to_param
    slug
  end

  def self.chooseables
    @chooseables ||= all.collect { |record| [record.name, record.id] }
  end
end

app/models/killer_achievement.rb
class KillerAchievement < ApplicationRecord
  belongs_to :killer
end

app/models/leaderboard_stat.rb
class LeaderboardStat < ApplicationRecord
  belongs_to :user

  def readonly?
    true
  end
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :series
  has_many :achievements, class_name: "LocationAchievement"
  has_one_attached :logo
  has_one_attached :icon

  validates :name, presence: true

  def to_param
    slug
  end

  def self.chooseables
    @chooseables ||= all.collect { |record| [record.name, record.id] }
  end
end

app/models/location_achievement.rb
class LocationAchievement < ApplicationRecord
  belongs_to :location
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :user
  belongs_to :final_girl
  belongs_to :killer
  belongs_to :location
end

app/models/series.rb
class Series < ApplicationRecord
  has_many :killers
  has_many :locations
  has_many :final_girl_series
  has_many :final_girls, through: :final_girl_series

  validates :name, presence: true

  def ordered_killers
    killers.order(:name)
  end

  def ordered_locations
    locations.order(:name)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
    :validatable

  has_many :plays

  has_many :user_killer_achievements
  has_many :killer_achievements, through: :user_killer_achievements

  has_many :user_location_achievements
  has_many :location_achievements, through: :user_location_achievements

  has_many :user_final_girls, inverse_of: :user, dependent: :destroy
  has_many :final_girls, through: :user_final_girls

  accepts_nested_attributes_for :user_killer_achievements
  accepts_nested_attributes_for :user_location_achievements
end

app/models/user_final_girl.rb
class UserFinalGirl < ApplicationRecord
  belongs_to :user
  belongs_to :final_girl
end

app/models/user_killer_achievement.rb
class UserKillerAchievement < ApplicationRecord
  belongs_to :user
  belongs_to :killer_achievement
  belongs_to :location, optional: true

  scope :completed,
        ->(ids) { where(killer_achievement: ids).where(completed: true) }
  scope :not_completed,
        ->(ids) { where(killer_achievement: ids).where(completed: false) }
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  private

  def set_user
    @user = GravatarDecorator.new(current_user)
  end

  def authorize_model
    authorize controller_name.classify.constantize
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < AuthController
  def show
    @facade = Dashboard::ShowFacade.new current_user, params
  end
end

app/controllers/killers_controller.rb
# frozen_string_literal: true

class KillersController < AuthController
  before_action :authorize_model, except: %i[index show]

  def index
    @facade = Killer::IndexFacade.new current_user, params
  end

  def show
    @facade = Killer::ShowFacade.new current_user, params
  end

  def new
    @killer = Killer.new
  end

  def create
    @killer = Killer.new killer_params

    if @killer.save
      redirect_to killers_url, notice: "Killer was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    killer
  end

  def update
    killer.update killer_params
    redirect_to killer_path(killer), notice: "Killer updated."
  end

  private

  def killer
    @killer ||= authorize Killer.find_by(slug: params[:slug])
  end

  def killer_params
    params.require(:killer).permit(:name, :slug, :series_id, :icon, :logo)
  end
end

app/controllers/plays_controller.rb
class PlaysController < AuthController
  def index
    @facade = Play::IndexFacade.new current_user
  end

  def new
    @facade = Play::NewFacade.new current_user
  end

  def create
    @facade = Play::NewFacade.new current_user, play_params

    if @facade.model.save
      redirect_to plays_url, notice: "Play was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @facade = Play::EditFacade.new current_user, params
  end

  def update
    @facade = Play::EditFacade.new current_user, params, strong_params: play_params

    if @facade.model.save
      redirect_to plays_url, notice: "Play was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    play.destroy

    redirect_to plays_url, notice: "Play was successfully destroyed.", status: :see_other
  end

  private

  def play
    @play ||= Play.find(params[:id])
  end

  def play_params
    params.require(:play).permit(
      :final_girl_id,
      :killer_id,
      :location_id,
      :created_at,
      :is_win,
      :extreme_horror_mode
    )
  end
end

app/controllers/series_controller.rb
# frozen_string_literal: true

class SeriesController < AuthController
  before_action :authorize_model

  def index
    @facade = Series::IndexFacade.new current_user, params
  end

  def new
    @series = Series.new
  end

  def create
    @series = Series.create series_params

    if @series.save
      redirect_to series_index_url, notice: "Series was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    series
  end

  def update
    series.update series_params
    redirect_to series_path(series), notice: "Series updated."
  end

  private

  def series
    @series ||= authorize Series.find(params[:id])
  end

  def series_params
    params.require(:series).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < AuthController
  def show
  end

  def update
    current_user.update!(user_params)
    flash.notice = "Your changes have been saved."

    redirect_back(fallback_location: root_path)
  end

  def user_params
    params.require(:user).permit(
      :username,
      {
        user_killer_achievements_attributes: %i[
          id
          killer_achievement_id
          location_id
          completed
        ],
      },
      {
        user_location_achievements_attributes: %i[
          id
          location_achievement_id
          killer_id
          completed
        ],
      },
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  ActionView::Base.default_form_builder = TailwindFormBuilder

  def render_component(component_path, collection: nil, **, &block)
    component_klass = "#{component_path.classify}Component".constantize

    if collection
      render component_klass.with_collection(collection, **), &block
    else
      render component_klass.new(**), &block
    end
  end
end

app/helpers/user_final_girls_helper.rb
module UserFinalGirlsHelper
end

app/views/dashboard/show.html.erb
<div class="container mx-auto">
  <%= render PageTitleComponent.new title: "Dashboard" %>
  <div class="text-zinc-50 grid grid-cols-1 md:grid-cols-3 gap-4 mt-8">
    <div class="md:col-span-2">
      <div class="mb-8">
        <h3 class="font-bold text-xl mb-2">Killer Achievements Progress</h3>
        <div class="flex flex-row">
          <div class="overflow-hidden h-8 text-xs flex rounded bg-zinc-200 w-full">
            <div style="width: <%= @facade.all_killer_achievement_progress %>%" class="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-primary"></div>
          </div>
          <div class="w-20 flex justify-center items-center font-bold">
            <%= @facade.all_killer_achievement_progress %>%
          </div>
        </div>
      </div>
      <div>
        <h3 class="font-bold text-xl mb-2">Location Achievements Progress</h3>
        <div class="flex flex-row">
          <div class="overflow-hidden h-8 text-xs flex rounded bg-zinc-200 w-full">
            <div style="width: <%= @facade.all_location_achievement_progress %>%" class="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-primary"></div>
          </div>
          <div class="w-20 flex justify-center items-center font-bold">
            <%= @facade.all_location_achievement_progress %>%
          </div>
        </div>
      </div>
    </div>
    <div class="flex flex-col justify-center items-center mt-8 md:mt-0">
      <h3 class="font-bold text-xl mb-2">Win/Loss</h3>
      <%= pie_chart @facade.play_chart_data, donut: true, legend: false, suffix: "%", dataset: {borderWidth: 5, borderColor: "#18181b"}, library: {plugins: {title:{color: "#fafafa"}}}  %>
    </div>
  </div>
</div>

app/views/series/_form.html.erb
<%= form_for @series do |f| %>
  <%= f.errors @series %>
  <div class="mb-4">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= link_to "Back", series_index_path, class: "button bg-transparent hover:bg-zinc-800 mr-2" %>
  <%= f.submit %>
<% end %>

app/views/series/_series.html.erb
<tr id="<%= dom_id series %>" class="odd:bg-zinc-600 even:bg-zinc-700 text-zinc-50 flex flex-col relative sm:table-row first:rounded-t-lg last:rounded-b-lg">
  <td class="text-left py-3 px-4">
    <div class="flex flex-row items-center">
      <span class="font-bold"><%= series.name %></span>
    </div>
  </td>
  <td class="py-3 px-4 absolute top-0 right-0 sm:relative">
    <div class="flex justify-end items-center">
      <%= link_to edit_series_path(series), class: "button h-7 w-7 bg-transparent hover:bg-zinc-800 mr-2" do %>
        <i class="fa-solid fa-pen-to-square"></i>
      <% end %>
      <%= button_to series_path(series), method: :delete, class: "button h-7 w-7 bg-transparent hover:bg-primary", form: { data: { turbo_confirm: "Are you sure you want to delete this play?" } } do %>
        <i class="fa-solid fa-trash-can"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/series/edit.html.erb
<%= render "form" %>

app/views/series/index.html.erb
<div class="text-zinc-50 flex flex-row justify-between items-center mb-4 w-full">
  <h1 class="font-display text-primary text-4xl">Series</h1>
  <%= link_to "Add Series", new_series_path, class: "button" %>
</div>
<table class="table-auto border-collapse min-w-full text-white">
  <thead class="hidden sm:table-header-group">
    <tr>
      <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Name</th>
      <th class="text-center py-3 px-4 uppercase font-semibold text-sm"></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "series", collection: @facade.collection %>
  </tbody>
</table>

app/views/series/new.html.erb
<%= render "form" %>